### ISSUE TITLE
Don't use both `mtime.clock` and `mtime.clock.os`

### ISSUE THREAD

**Issue by dbuenzli** [Gbury/archsat#2]
`mtime.clock.os` is sufficient [here](https://github.com/Gbury/archsat/blob/322fbefa4a58023ddafb3fa1a51f8199c25cde3d/src/_tags#L43). Specifying both fails with the latest version of `mtime`.

**Comment by Gbury** [comment]
Should be fixed by 3d2f2b596b641d0d14852f8f0718221d73a075a4
